const path = require('path');

module.exports = (_env, argv) => {
    const clientMode = argv.mode ?? 'production';

    // Browser bundles. Source lives outside the static public directory so
    // every JavaScript file served from public/javascripts is generated by
    // webpack.
    const client = {
        name: 'client',
        mode: clientMode,
        devtool: clientMode === 'development' ? 'source-map' : false,
        entry: {
            'plot-page': './client/index.js',
            'folder-picker': './client/components/gtc-output-picker.js',
            'input-generator': './client/gtc-input/input-generate.js',
        },
        target: 'web',
        output: {
            path: path.join(__dirname, 'public/javascripts'),
            filename: '[name].js',
            clean: true,
        },
    };

    // Server bundle — Express app
    const server = {
        name: 'server',
        mode: 'production',
        entry: './server/server.js',
        target: 'node',
        output: {
            path: __dirname,
            filename: 'server-prod.js',
        },
        node: {
            __dirname: false,
            __filename: false,
        },
    };

    return [client, server];
};
